server {
    listen 80;
    server_name localhost;
    
    # 🚀 LA SOLUCIÓN AL ERROR 413: Permitir subidas de hasta 50 Megabytes
    client_max_body_size 100M;

    root /usr/share/nginx/html;
    index index.html;

    # 1. Rutas de Angular
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. 🚀 PUENTE AL BACKEND (Proxy Inverso)
    location /api/ {
        # Pasamos la petición internamente al puerto 8000
        proxy_pass http://206.189.118.99:8000;
        
        # Mantenemos los datos originales del cliente
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}