server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Esto asegura que las rutas de Angular (como /chat o /login) no den error 404
    location / {
        try_files $uri $uri/ /index.html;
    }
}