version: '3.8'

services:
  postgres_local:
    image: postgres:17-alpine
    container_name: bp_postgres_local
    restart: always
    environment:
      POSTGRES_USER: superadmin_bp
      POSTGRES_PASSWORD: bp_secure_password_2026!
      POSTGRES_DB: blackpenguin_core
    ports:
      - "5433:5432"