from __future__ import annotations

from collections.abc import Mapping


ACCESS_RESTRICTED_MESSAGE = (
    "This website requires browser security verification, so I couldn't read its "
    "content automatically. You can upload a document, retry once, or continue manually."
)

PROTECTED_FILE_MESSAGE = (
    "I couldn't analyze this file because it is password-protected or encrypted. "
    "Upload an unlocked copy or continue manually."
)
UNREADABLE_FILE_MESSAGE = (
    "I couldn't read this file because it appears to be damaged or is not a valid "
    "supported document. Upload another copy or continue manually."
)
NO_READABLE_CONTENT_MESSAGE = (
    "I couldn't find readable text in this document. It may contain scanned pages "
    "without OCR. Upload a text-searchable copy or continue manually."
)
PROTECTED_OR_LEGACY_OFFICE_MESSAGE = (
    "This Office file appears to be encrypted, password-protected, or saved in an "
    "older unsupported format. Upload an unlocked DOCX or XLSX copy, or continue manually."
)


class SourceFileError(Exception):
    """Base class for stable, user-safe file processing failures."""

    code = "source_file_error"
    default_message = UNREADABLE_FILE_MESSAGE

    def __init__(self, message: str | None = None) -> None:
        super().__init__(message or self.default_message)


class ProtectedFileError(SourceFileError):
    code = "protected_file"
    default_message = PROTECTED_FILE_MESSAGE


class UnreadableFileError(SourceFileError):
    code = "unreadable_file"
    default_message = UNREADABLE_FILE_MESSAGE


class NoReadableContentError(SourceFileError):
    code = "no_readable_content"
    default_message = NO_READABLE_CONTENT_MESSAGE


class ProtectedOrLegacyOfficeError(SourceFileError):
    code = "protected_or_legacy_office"
    default_message = PROTECTED_OR_LEGACY_OFFICE_MESSAGE


class AccessRestrictedError(Exception):
    """Raised when a remote site returns a browser-verification challenge."""

    code = "access_restricted"

    def __init__(self, message: str = ACCESS_RESTRICTED_MESSAGE) -> None:
        super().__init__(message)


def raise_for_access_restriction(
    *,
    status_code: int,
    headers: Mapping[str, str],
    body: bytes,
) -> None:
    """Classify structural challenge signals without attempting to bypass them."""

    normalized_headers = {str(key).lower(): str(value).lower() for key, value in headers.items()}
    sample = body[:200_000].lower()
    has_challenge_header = normalized_headers.get("cf-mitigated") == "challenge"
    has_cloudflare_ray = "cf-ray" in normalized_headers
    server = normalized_headers.get("server", "")
    has_cloudfront = "cloudfront" in server or "x-amz-cf-id" in normalized_headers
    challenge_markers = (
        b"/cdn-cgi/challenge-platform/",
        b"cf-chl-",
        b"cf_clearance",
        b"challenge-form",
    )
    has_challenge_markup = any(marker in sample for marker in challenge_markers)
    has_blocked_markup = any(marker in sample for marker in (
        b"request blocked", b"access denied", b"generated by cloudfront",
    ))

    if has_challenge_header or has_challenge_markup or (
        status_code in {403, 503} and has_cloudflare_ray
    ) or (
        status_code == 403 and has_cloudfront and has_blocked_markup
    ):
        raise AccessRestrictedError()
    if status_code in {401, 403}:
        raise AccessRestrictedError(
            "This website rejected automated access, so I couldn't read its content. "
            "You can upload a document, retry manually, or continue with manual entry."
        )
